# Generated by Django 5.0.2 on 2024-07-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user',
        ),
    ]
