# Generated by Django 5.0.2 on 2024-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_API', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
